# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# Ejecuta un update al crear las maquinas, y les instala Java a ambas.
	config.vm.provision "shell", inline: <<-SCRIPT
		sudo apt-get update -y
		sudo apt-get install default-jre -y
		sudo apt-get install default-jdk -y
		export CLASSPATH='.:/vagrant/mongo-java-driver-3.9.1.jar'
	SCRIPT

# Crea la VM la cual contiene el scritp en Java para dar de alta un usuario en la base de datos.
# Se le asigna una ip estática.
	config.vm.define :javaVM do |javaVM|
		javaVM.vm.hostname = "javaVM"
		javaVM.vm.box = "ubuntu/xenial64"
		javaVM.vm.network "private_network", ip: "192.168.50.4"
	end

# Crea la VM que contiene la base de datos de mongoDB, el cual se instala al iniciar por primera vez la VM.
# Se le asigna una ip estática.
	config.vm.define :mongoVM do |mongoVM|
		mongoVM.vm.hostname = "mongoVM"
		mongoVM.vm.box = "ubuntu/xenial64"
		mongoVM.vm.network "private_network", ip: "192.168.50.5"
		mongoVM.vm.provision "shell", inline: <<-MONGO
			sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
			echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
			sudo apt-get update -y
			sudo apt-get install -y mongodb-org
			sudo service mongod start
		MONGO
	end

end
