version: '3'
services:
    write_app:
        build: .
        command: java People
        depends_on:
            - db
        ports:
            - "80:9000"
    read_app:
        build: .
        command: java ReadPeople
        depends_on:
            - db
        ports:
            - "81:9001"
    db:
        image: mongo
        volumes:
            - "/opt/mongodb:/data/db"
